### ISSUE TITLE
Procedural mesh grid tutorial problem

### ISSUE THREAD

**Issue by jaroslavknotek** [mitsuba-renderer/mitsuba-tutorials#10]
In the [Mesh IO tutorial](https://github.com/mitsuba-renderer/mitsuba-tutorials/blob/master/how_to_guides/mesh_io_and_manipulation.ipynb), there is a section about procedural mesh which doesn't work for different variants.

In my case, it didn't work for `llvm_ad_rgb` because I don't have libLLVM.so installed. But it worked with `cuda_ad_rgb`. However, the code doesn't work with `scalar_rgb` or `scalar_spectral`.  It ends up failing with this error

```
---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
Cell In [5], line 33
     24 mesh = mi.Mesh(
     25     "wavydisk",
     26     vertex_count=N,
   (...)
     29     has_vertex_texcoords=False,
     30 )
     32 mesh_params = mi.traverse(mesh)
---> 33 mesh_params["vertex_positions"] = dr.ravel(vertex_pos)
     34 mesh_params["faces"] = dr.ravel(face_indices)
     35 print(mesh_params.update())

File ~/.cache/pypoetry/virtualenvs/synthdata-Cub-fwJX-py3.9/lib/python3.9/site-packages/mitsuba/python/util.py:81, in SceneParameters.__setitem__(self, key, value)
     79             raise e
     80 else:
---> 81     self.set_property(cur, value_type, value)

RuntimeError: Unable to cast Python instance to C++ type (#define PYBIND11_DETAILED_ERROR_MESSAGES or compile in debug mode for details)
```

I tried to work around it by casting the result of dr.ravel into numpy array with types float16,float32 and float 64 but it din't help much - the error disappeared but there was no output mesh printed. After removing the numpy casting and setting the variant back to `cuda_ad_rgb` everything started working.

Using the preinstalled `cuda_ad_rgb` is not a feasible solution as I need to perform scalar rendering within `scalar_spectral` which in turn (as described above) disqualified the use of procedural mesh. Using `cuda_ad_specral` to have both is not possible for me as I can't build it from code. 

Is the fact that you can't use `scalar_spectral` for creating procedural mesh something desired or is it a bug?

**Comment by jaroslavknotek** [comment]
Trying to do procedural grid with `numpy` instead of `drjit` worked in `scalar_spectral`.

The code:
```python
vertex_pos = np.zeros((rows*columns,3))
vertex_pos[:columns,0] = np.linspace(0,2,columns)
vertex_pos[columns:,0] = np.linspace(0,2,columns)
vertex_pos[columns:,1] = np.ones((columns,))

face_indices = []
for i in range(rows-1):
    for j in range(columns-1):
        # a -- b
        # | -- |
        # c -- d
        idxs = np.array([(i,j),(i,j+1),(i+1,j),(i+1,j+1)]).T
        a,b,c,d= np.ravel_multi_index(idxs,(rows,columns))
        
        face_indices.append([a,b,c])
        face_indices.append([c,b,d])

mesh_params = mi.traverse(mesh)
mesh_params["vertex_positions"] = np.ravel(vertex_pos)
mesh_params["faces"] = np.ravel(face_indices)
```
produced and image with the plane.

I guess that the problem is related todrjit, not to mitsuba.

I'd like to get it confirmed before closing this issue. Thanks

**Comment by Speierers** [comment]
Hi @jaroslavknotek ,

Indeed this code is only suppose to work for the JIT variants of the renderer (e.g. the non-scalar variants). This is true for most of the tutorials in the documentation actually. If you can't install LLVM on you system, switching to Numpy is a good alternative.
