### ISSUE TITLE
Broken drjit links in tutorials

### ISSUE THREAD

**Issue by spratyey** [mitsuba-renderer/mitsuba-tutorials#17]
Hi,
I'm currently going through the inverse rendering tutorials and noticed some links pointing to drjit documentation are broken.

A couple of instances of this:
1. In [the Optimization tutorial](https://mitsuba.readthedocs.io/en/stable/src/inverse_rendering/gradient_based_opt.html), the [link in the footer to dr.backward](https://drjit.readthedocs.io/en/latest/src/api_reference.html#drjit.backward) results in a 404. The correct page to link to seems to be [this](https://drjit.readthedocs.io/en/latest/reference.html#drjit.backward)
2. In [the Forward Inverse rendering tutorial](https://mitsuba.readthedocs.io/en/stable/src/inverse_rendering/forward_inverse_rendering.html), inline links to dr.forward and dr.grad are broken too.

**Comment by spratyey** [comment]
@Speierers @njroussel May I go ahead and work on a PR to fix this?

**Comment by njroussel** [comment]
Hi @spratyey
Yes of course, please open a PR for it. If you don't have time right now, I should be able to get to this in a couple of days.

**Comment by spratyey** [comment]
Sure, I'll do it. I've just started using Mitsuba for my undergrad research, and would like to explore the codebase as I go. 
This issue (albeit rather trivial) seems like a good starting point haha.

**Comment by njroussel** [comment]
@spratyey  I fixed the ones you reported as I had to fixer other links, thanks for signaling them!
