### ISSUE TITLE
../scenes/shadow_art.xml missing from scenes.zip

### ISSUE THREAD

**Issue by foshyjoshy** [mitsuba-renderer/mitsuba-tutorials#20]
Running through the projective_sampling_integrators.ipynb tutorial and have found that the shadow_art.xml is missing from the scenes.zip

https://rgl.s3.eu-central-1.amazonaws.com/scenes/tutorials/scenes.zip

**Comment by njroussel** [comment]
Hello @foshyjoshy 

Indeed, thank you for reporting this. I'll get that fixed asap. In the meantime, all resources are also available in this repository: https://github.com/mitsuba-renderer/mitsuba-tutorials/tree/master/scenes
