### ISSUE TITLE
Overfitting in Radiance Field Reconstruction?

### ISSUE THREAD

**Issue by tszirr** [mitsuba-renderer/mitsuba-tutorials#9]
I experimented with the RF tutorial about the time of release, but judging from the git history this should still be relevant: 
When looking at the optimized result from various angles in-between the trained perspectives, it becomes apparent that the training data set is too small, resulting in rather extreme overfitting to the training perspectives:
https://user-images.githubusercontent.com/4539627/191536037-3b71efe4-28c2-43f7-90e1-c6e564648cee.mp4
Using 70 perspectives instead of 7 and adding a bit of randomization to lookat/offset, quality for training perspectives is a bit worse, but overall the result is much improved :)
https://user-images.githubusercontent.com/4539627/191536110-4541e55f-0142-46ed-9a83-74c22407ef21.mp4

Anyways, very cool that you provide a RF example! This should be an easy fix, if you haven't already addressed it internally.

**Comment by Speierers** [comment]
Hi @tszirr ,

Thanks for reporting this. The tutorials are only meant to showcase how the framework can be used to write such optimization pipelines. A lot of extra work can be done to improve the actual results but we decided to keep the tutorials simple and leave that to the users. We also want the tutorials to be fast and to run on any machine (e.g. laptops), hence we keep some of the hyperparameters low on purpose.

Glad to see that with such minor tweaks you already get much better results!

**Comment by ALevitskyy** [comment]
Could you, please, provide some pointers on what can be done to improve the generalization to novel angles?
Is there some way to regularize the radiance field to make it overfit less?

**Comment by ALevitskyy** [comment]
Thank you!
